update

diff --git a/apps/node b/apps/node
--- a/apps/node
+++ b/apps/node
@@ -1,10 +1,25 @@
 #!/bin/bash
 
-echo "Installing node.js"
+echo "Installing nvm..."
 if gum spin --title "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash" -- curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash \
-   && \. "$HOME/.nvm/nvm.sh" \
-   && gum spin --title "nvm install 22" -- nvm install 22 \
-   && echo -e "\n\n# nvm\n\nexport NVM_DIR="$HOME/.nvm"\n[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm\n[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion" >> /root/.zshrc;
+   && \. "$HOME/.nvm/nvm.sh";
+then
+  echo "✅ node.js installed"^
+else
+  echo "❌ Failed to install node.js."
+  exit 1
+fi
+
+echo "Init nvm..."
+echo -e "export NVM_DIR=\"\$HOME/.nvm\"" > /usr/local/etc/sh/nvm.sh
+echo -e "[ -s \"\$NVM_DIR/nvm.sh\" ] && \\. \"\$NVM_DIR/nvm.sh\"" >> /usr/local/etc/sh/nvm.sh
+echo -e "[ -s \"\$NVM_DIR/bash_completion\" ] && \\. \"\$NVM_DIR/bash_completion\"" >> /usr/local/etc/sh/nvm.sh
+echo -e "export PATH=$NVM_DIR:$PATH"
+source /usr/local/etc/sh/nvm.sh
+
+echo "Installing node.js..."
+if gum choose --header="Choose node version to install" --selected="22" "18" "20" "22" "24" \
+   | xargs -I{} bash -c 'gum spin --title "nvm install {}" -- bash -c "source /usr/local/etc/sh/nvm.sh && nvm install {}"';
 then
   echo "✅ node.js installed"^
 else
